Implement rsync, SSH agent setup, and variable sanitization for pack upload

diff --git a/.github/workflows/create-pack.yml b/.github/workflows/create-pack.yml
--- a/.github/workflows/create-pack.yml
+++ b/.github/workflows/create-pack.yml
@@ -1,27 +1,67 @@
 name: Create Pack
 on:
   push:
-    branches-ignore:
-      - master
-      - main
+    branches:
+      - "*"
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Get branch name
-      id: branch-name
-      uses: tj-actions/branch-names@v6.4
-
-    - name: Create Pack
-      uses: appleboy/ssh-action@v0.1.7
+    # Set up the ssh agent (easier & faster than creating folders, config, and authorized_keys)
+    - uses: webfactory/ssh-agent@v0.9.0
       with:
-        host: ${{ secrets.HOST }}
-        USERNAME: ${{ secrets.USERNAME }}
-        PORT: ${{ secrets.PORT }}
-        KEY: ${{ secrets.SSH }}
-        script: |
-          [ ! -d "./packs/Faithful-Java-32x/${{ steps.branch-name.outputs.current_branch }}" ] && exit 1
-          cd "./packs/Faithful-Java-32x/${{ steps.branch-name.outputs.current_branch }}"
-          git pull
-          zip -r "Faithful 32x - ${{ steps.branch-name.outputs.current_branch }} Experimental.zip" . -x "*.git*" -x "*.github*" -x ".gitignore"
-          mv "Faithful 32x - ${{ steps.branch-name.outputs.current_branch }} Experimental.zip" "/var/www/html/database.faithfulpack.net/packs/32x-Java/Experimental"
+        ssh-private-key: ${{ secrets.SSH }}
+
+    # Saves the branch files on the runner
+    - name: Checkout
+      uses: actions/checkout@v6
+      with: 
+        fetch-depth: 0
+
+    # Verifies the pipeline has the necessary data to create a pack
+    - name: "Verify Contents"
+      id: "verify_step"
+      run: |
+        echo "Verifying required files and directories..."
+        REQUIRED_ITEMS=(
+          "assets/"
+          "pack.mcmeta"
+          "pack.png"
+          "LICENSE"
+        )
+
+        for ITEM in "${REQUIRED_ITEMS[@]}"; do
+          if [ ! -e "$ITEM" ]; then
+            echo "Files $ITEM is mising. Exiting..."
+            exit 1
+          fi
+        done
+
+        echo "All files have been found."
+
+    # Not sure if this is needed but local testing with `act` requires it (medium-image used)
+    - name: Install rsync
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y rsync
+
+    # 1 - zips the pack
+    # 2 - sanitizes the pack name removing spaces (maybe not needed but it can break things), 
+    # 3 - creates subdirectories, rsync not always does that
+    # 4 - transfers file to server
+    - name: "Remote Upload"
+      if: steps.verify_step.outcome == 'success'
+      run: |
+        echo "Creating resource pack zip..."
+        ls -ls ~
+        zip -r ${{ vars.PACK_NAME }}.zip assets pack.mcmeta pack.png LICENSE
+
+        echo "Sending file to the server"
+        
+        SANITIZED_REF_NAME=$(echo "${{ github.ref_name }}" | tr ' ' '-')
+
+        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mkdir -p ~/var/www/html/database.faithfulpack.net/packs/${SANITIZED_REF_NAME}"
+        rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" ${{ vars.PACK_NAME }}.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/var/www/html/database.faithfulpack.net/packs/${SANITIZED_REF_NAME}
+
+        echo "File uploaded to ~/var/www/html/database.faithfulpack.net/packs/${SANITIZED_REF_NAME}"
